# Generated by Django 4.2.7 on 2023-11-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_image_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimum_amount', models.IntegerField()),
                ('maximum_amount', models.IntegerField()),
                ('percentage', models.CharField(max_length=5)),
                ('hours', models.CharField(max_length=100)),
            ],
        ),
    ]
