# Generated by Django 4.2.7 on 2023-11-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_payment_method_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_methold',
            new_name='payment_method',
        ),
    ]
