# Generated by Django 4.2.7 on 2023-11-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_payment_methold_transaction_payment_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_Method',
            new_name='PaymentMethod',
        ),
    ]
