# Generated by Django 4.2.7 on 2023-11-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.ImageField(null=True, upload_to='Transactions'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Successful', 'Successful'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
    ]
