# Generated by Django 4.2.7 on 2023-11-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_recommenation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommenation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
