# Generated by Django 4.2.7 on 2023-11-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_recommenation_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommenation',
            new_name='Recommedation',
        ),
    ]
