# Generated by Django 4.2.7 on 2023-11-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_recommenation_recommedation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommedation',
            new_name='Recommendation',
        ),
    ]
