# Generated by Django 4.2.7 on 2023-11-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_recommedation_recommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
