# Generated by Django 4.2.7 on 2023-11-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='Withdrawal', max_length=50),
        ),
    ]
