# Generated by Django 4.2.7 on 2023-11-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='E:\\PROGRAMS\\PYTHON\\INVESTMENT\\project\\statics\\profile.jpg', null=True, upload_to='user/'),
        ),
    ]
