# Generated by Django 4.2.7 on 2023-11-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/profile.jpg', null=True, upload_to='user/'),
        ),
    ]
