# Generated by Django 4.2.7 on 2023-12-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
