# Generated by Django 4.2.7 on 2023-12-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_investment_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
