# Generated by Django 4.2.7 on 2023-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_investment_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='profit',
            field=models.FloatField(),
        ),
    ]
