# Generated by Django 4.2.7 on 2023-12-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_investment_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
