# Generated by Django 4.2.7 on 2023-12-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_investment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
